### ISSUE TITLE
viaeagx

### ISSUE THREAD

**Issue by FatalEagler** [WorldEditAxe/eaglerproxy#14]
could you maybe make it so it can also allow you to select a server version to connect to servers with a higher version?

**Comment by WorldEditAxe** [comment]
is it possible? yes
but would it be plausible? no, not really (it wouldn't even be part of this project)

since the proxy accepts eaglercraftx connections and emulates a normal 1.8.9 client (rather than a bungeecord connection), you can probably hook it up to any viaaas server, as long as it accepts offline connections (or modify the eagpaas plugin to directly connect to the online viaaas server, which I can help you with)

**Comment by WorldEditAxe** [comment]
you don't need to worry about issues regarding compatibility; if 1.8.8 supports it eagler definitely will
